---

- hosts: myhost
  tasks:
    - name: copy over vim settings
      copy:
        src: .vimrc
        dest: ~/.vimrc
    - name: set bash editor as vim
      lineinfile:
        path: ~/.bashrc
        state: present
        line: 'export EDITOR="vim"'
    - name: set bash command prompt
      lineinfile:
        path: ~/.bashrc
        state: present
        line: 'PS1="\u:\W\$ "'
    # - name: Turn off bell in terminal
    #   become: true
    #   lineinfile:
    #     path: /etc/inputrc
    #     state: present
    #     line: 'set bell-style visible'

# TODO vim python-mode https://github.com/python-mode/python-mode
