---

- hosts: myhost
  vars:
    atom_packages_packages:
      - linter-pycodestyle
      - linter-flake8
      - autocomplete-python
      - atom-django
  roles:
    - hnakamur.atom-packages
  tasks:  # to support atom packages above
    - name: pip install pycodestyle within user home directory
      pip:
        name: pycodestyle
        extra_args: --user
    - name: Install pip flake8 within user home directory
      pip:
        name: flake8
        extra_args: --user
    - name: remove scl-utils so flake8 can work in fedora atom
      become: yes
      package:
        name: scl-utils
        state: absent

# TODO package tree-view hide_vcs_ignored_files=true
# TODO autocomplete-plus keymap_for_comfirming_a_suggestions=tab
