---

- name: Install Docker Engine on Fedora or Ubuntu
  hosts: myhost
  become: true
  tasks:
    - name: Add Docker GPG key on Fedora
      rpm_key:
        key: https://download.docker.com/linux/fedora/gpg
        state: present
      when:
        ansible_distribution != "Ubuntu"  # TODO: Set to == ~"RH|Fedora"
    - name: Add Docker GPG key on Ubuntu
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when:
        ansible_distribution == "Ubuntu"
    - name: Set up the repository on Fedora
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'
        owner: root
        group: root
      when:
        ansible_distribution != "Ubuntu"  # TODO: Set to == ~"RH|Fedora"
    - name: Set up the repository on Ubuntu
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      when:
        ansible_distribution == "Ubuntu"
    - name: Install docker engine
      ansible.builtin.package:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        state: latest
    - name: Make sure docker service is running and enabled to start on boot
      ansible.builtin.service:  # note: error w/ ansible.builtin.systemd_service not resolved with ubuntu ansible 2.9.6
        name: docker  # TODO: used systemd_service w/ fedora test this w/ fedora
        state: started
        enabled: true
    - name: Ensure the docker group exists
      ansible.builtin.group:
        name: docker
        state: present
    - name: Add user to the docker group
      ansible.builtin.user:
        name: "{{ user }}"
        groups: docker
        append: true  # afterwards needs one: `$ newgrp docker`, logout, or reboot
