---

- name: Set config for common terminal tools
  hosts: myhost
  tasks:
    - name: bashrc settings
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        state: present
        line: '{{item}}'
      with_items:
        - 'PS1="\u:\W\$ "  # user-added prompt format'
        - 'export EDITOR="vim"  # user-added'
        - '# export GIT_COMPLETION_CHECKOUT_NO_GUESS=1  # user-added stops git auto-complete remote branches'
        - '# export V="source /home/awc/code/env/bin/activate"  # user-added shortcut for common python env'
    - name: vim tab settings
      ansible.builtin.blockinfile:
        path: ~/.vimrc
        marker: '" {mark} ANSIBLE MANAGED BLOCK'
        block: |
          " For indents that consist of 4 space characters but are entered with the tab key:
          set tabstop=8       " width of a tab measured in spaces, effectively max width of a tab character
          set softtabstop=0   " if non-zero, a mix of spaces and tabs can be used
          set expandtab       " tabs are spaces, also softtabstop will be ignored and spaces will be forced
          set shiftwidth=4    " size of an indent
          set smarttab        " tab key goes to next indent
    - name: Additional vim settings
      ansible.builtin.lineinfile:
        path: ~/.vimrc
        state: present
        line: '{{item}}'
      with_items:
        - 'set bg=dark  " user-added, dark background'
        - 'set visualbell " user-added, visual cue instead of audible beep'
        - 'set number  " user-added show line numbers'
